## End-to-End Data Analytics: Part 1 (Cleaning & EDA)

#### Retail Analysis using Python: Customer Behavior

In [1]:
!mamba install pandas

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 2.726900000002235 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ pandas                        3.0.2                         np22py313h9d9dc1e_0           emscripten-forge
+ python-tzdata                 2026.2                        pyhd8ed1ab_0                  conda-forge
- pip                           25.3                          pyh145f28c_0                  conda-forge

In [2]:
import pandas as pd

In [3]:
df_shopping = pd.read_csv('cust_shopping.csv')

In [4]:
df_shopping.head(11)

,Cust ID,Age,Gender,Item Purchased,Category,Amt (USD),Location,Size,Color,Season,Rating,Subscription,Shipping Type,Discount Applied,Promo Code Used,Prev Purchase,Payment Method,Frequency of Purchases,Unnamed: 18
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,NaN
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,NaN
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,NaN
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,NaN
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,NaN
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly,NaN
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly,NaN
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly,NaN
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually,NaN
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly,NaN
10,11,53,Male,Shoes,Footwear,34,Arkansas,L,Purple,Fall,4.1,Yes,Store Pickup,Yes,Yes,26,Bank Transfer,Bi-Weekly,NaN

In [5]:
df_shopping.info()

<class 'pandas.DataFrame'>
RangeIndex: 3902 entries, 0 to 3901
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Cust ID                 3902 non-null   int64
 1   Age                     3902 non-null   int64
 2   Gender                  3902 non-null   str
 3   Item Purchased          3902 non-null   str
 4   Category                3902 non-null   str
 5   Amt (USD)               3902 non-null   int64
 6   Location                3902 non-null   str
 7   Size                    3902 non-null   str
 8   Color                   3902 non-null   str
 9   Season                  3902 non-null   str
 10  Rating                  3865 non-null   float64
 11  Subscription            3902 non-null   str
 12  Shipping Type           3902 non-null   str
 13  Discount Applied        3902 non-null   str
 14  Promo Code Used         3902 non-null   str
 15  Prev Purchase           3902 non-null   int64
 16  Payment Method          3902 non-null   str
 17  Frequency of Purchases  3902 non-null   str
 18  Unnamed: 18             0 non-null      float64
dtypes: float64(2), int64(4), str(13)
memory usage: 381.1 KB

#### Data Conversion: str to object

In [6]:
df_shopping['Gender'] = df_shopping['Gender'].astype('object')
df_shopping['Item Purchased'] = df_shopping['Item Purchased'].astype('object')
df_shopping['Category'] = df_shopping['Category'].astype('object')
df_shopping['Location'] = df_shopping['Location'].astype('object')
df_shopping['Size'] = df_shopping['Size'].astype('object')
df_shopping['Color'] = df_shopping['Color'].astype('object')
df_shopping['Season'] = df_shopping['Season'].astype('object')
df_shopping['Subscription'] = df_shopping['Subscription'].astype('object')
df_shopping['Shipping Type'] = df_shopping['Shipping Type'].astype('object')
df_shopping['Discount Applied'] = df_shopping['Discount Applied'].astype('object')
df_shopping['Promo Code Used'] = df_shopping['Promo Code Used'].astype('object')
df_shopping['Payment Method'] = df_shopping['Payment Method'].astype('object')
df_shopping['Frequency of Purchases'] = df_shopping['Frequency of Purchases'].astype('object')

In [7]:
df_shopping.info()

<class 'pandas.DataFrame'>
RangeIndex: 3902 entries, 0 to 3901
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Cust ID                 3902 non-null   int64
 1   Age                     3902 non-null   int64
 2   Gender                  3902 non-null   object
 3   Item Purchased          3902 non-null   object
 4   Category                3902 non-null   object
 5   Amt (USD)               3902 non-null   int64
 6   Location                3902 non-null   object
 7   Size                    3902 non-null   object
 8   Color                   3902 non-null   object
 9   Season                  3902 non-null   object
 10  Rating                  3865 non-null   float64
 11  Subscription            3902 non-null   object
 12  Shipping Type           3902 non-null   object
 13  Discount Applied        3902 non-null   object
 14  Promo Code Used         3902 non-null   object
 15  Prev Purchase           3902 non-null   int64
 16  Payment Method          3902 non-null   object
 17  Frequency of Purchases  3902 non-null   object
 18  Unnamed: 18             0 non-null      float64
dtypes: float64(2), int64(4), object(13)
memory usage: 381.1+ KB

In [8]:
df_shopping.describe(include = 'all')

,Cust ID,Age,Gender,Item Purchased,Category,Amt (USD),Location,Size,Color,Season,Rating,Subscription,Shipping Type,Discount Applied,Promo Code Used,Prev Purchase,Payment Method,Frequency of Purchases,Unnamed: 18
count,3902.000000,3902.000000,3902,3902,3902,3902.000000,3902,3902,3902,3902,3865.000000,3902,3902,3902,3902,3902.000000,3902,3902,0.0
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7,NaN
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months,NaN
freq,NaN,NaN,2653,171,1739,NaN,96,1756,177,1000,NaN,2849,675,2225,2225,NaN,677,584,NaN
mean,1951.500000,44.066889,NaN,NaN,NaN,59.764223,NaN,NaN,NaN,NaN,3.750505,NaN,NaN,NaN,NaN,25.356228,NaN,NaN,NaN
std,1126.554704,15.204456,NaN,NaN,NaN,23.679345,NaN,NaN,NaN,NaN,0.717148,NaN,NaN,NaN,NaN,14.444910,NaN,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
25%,976.250000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN,NaN
50%,1951.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN,NaN
75%,2926.750000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN,NaN
max,3902.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.100000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN,NaN

#### Dropped 'Anomaly' Column:

In [12]:
df_shopping = df_shopping.drop(['Unnamed: 18'], axis = 1)

In [13]:
df_shopping.isnull().sum()

Cust ID                    0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Amt (USD)                  0
Location                   0
Size                       0
Color                      0
Season                     0
Rating                    37
Subscription               0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Prev Purchase              0
Payment Method             0
Frequency of Purchases     0
dtype: int64

#### Removing Null value:

In [14]:
df_shopping['Rating'] = df_shopping.groupby('Category')['Rating'].transform(lambda x: x.fillna(x.median()))

In [15]:
df_shopping.isnull().sum()

Cust ID                   0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Amt (USD)                 0
Location                  0
Size                      0
Color                     0
Season                    0
Rating                    0
Subscription              0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Prev Purchase             0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [16]:
df_shopping.columns

Index(['Cust ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Amt (USD)',
       'Location', 'Size', 'Color', 'Season', 'Rating', 'Subscription',
       'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Prev Purchase',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

#### Snake Casing: for uniformity and consistency

In [17]:
df_shopping.columns = df_shopping.columns.str.lower()
df_shopping.columns = df_shopping.columns.str.replace(' ','_')

In [18]:
df_shopping.columns

Index(['cust_id', 'age', 'gender', 'item_purchased', 'category', 'amt_(usd)',
       'location', 'size', 'color', 'season', 'rating', 'subscription',
       'shipping_type', 'discount_applied', 'promo_code_used', 'prev_purchase',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [19]:
df_shopping = df_shopping.rename(columns = {'amt_(usd)':'amt_usd'})

#### Creating Column: Age buckets

In [20]:
# create a new column age_group:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df_shopping['age_group'] = pd.qcut(df_shopping['age'], q = 4, labels = labels)

In [22]:
df_shopping[['age', 'age_group']].head(5)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged

#### Create a column for 'Frequency Mapping':

In [23]:
# create new column purchase_frequency_days
freq_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df_shopping['purchase_freq_days'] = df_shopping['frequency_of_purchases'].map(freq_mapping)

In [24]:
df_shopping[['purchase_freq_days','frequency_of_purchases']].head(4)

   purchase_freq_days frequency_of_purchases
0                  14            Fortnightly
1                  14            Fortnightly
2                   7                 Weekly
3                   7                 Weekly

In [25]:
df_shopping.head(3)

,cust_id,age,gender,item_purchased,category,amt_usd,location,size,color,season,rating,subscription,shipping_type,discount_applied,promo_code_used,prev_purchase,payment_method,frequency_of_purchases,age_group,purchase_freq_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-aged,7

In [26]:
df_shopping[['discount_applied','promo_code_used']].head(4)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes

#### Dropping unnecessary column:
- 'discount_applied', 'promo_code_used' have the same results, so will drop promo_code_used column!

In [27]:
(df_shopping['discount_applied'] == df_shopping['promo_code_used']).all()

np.True_

In [28]:
df_shopping = df_shopping.drop('promo_code_used', axis = 1)

In [29]:
df_shopping.head(3)

,cust_id,age,gender,item_purchased,category,amt_usd,location,size,color,season,rating,subscription,shipping_type,discount_applied,prev_purchase,payment_method,frequency_of_purchases,age_group,purchase_freq_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7

#### Importing the cleaned Dataset to MySQL Workbench:

In [30]:
%pip install pandas sqlalchemy pymysql --upgrade

mambajs 0.19.13

Process pip requirements ...

Requirement pandas already handled by conda/micromamba/mamba.
Requirement typing-extensions already satisfied.
Successfully installed sqlalchemy-2.0.49 pymysql-1.1.3

In [31]:
import pandas as pd
import sqlalchemy

print(pd.__version__)
print(sqlalchemy.__version__)

3.0.2
2.0.49

In [33]:
# Can't connect:
# from sqlalchemy import create_engine

# # MySQL connection
# username = "root"
# password = "admin"
# host = "localhost" #127.0.0.1
# port = "3306"
# database = "customer_retail_db"

# engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# # Write DataFrame to MySQL
# table_name = "customer_data"   # choose any table name
# df_shopping.to_sql(table_name, engine, if_exists ="replace", index = False)

# # Read back sample
# pd.read_sql("SELECT * FROM customer_data LIMIT 5;", engine)

In [34]:
df_shopping.to_csv('cleaned_cust_dataset.csv', index = False)